FROM node:9-alpine
MAINTAINER Phoomparin Mano <phoomparin@gmail.com>

# Set node environment to development
ENV NODE_ENV development

# Setup the working directory
ENV app /opt/app
RUN mkdir -p $app
WORKDIR $app

# Install system dependencies
RUN apk update && apk --no-cache add python g++ make

# Install PM2
RUN yarn global add pm2

# Copy the package manifest and lockfiles over
COPY package.json yarn.lock /tmp/

# Add the yarn cache to speed up builds
ADD .yarn-cache.tgz /

# Install the application dependencies
RUN cd /tmp && yarn --pure-lockfile

# Link the node modules to the application directory
RUN cd $app && ln -s /tmp/node_modules

# Copy files into workspace
COPY package.json webpack.config.js $app/
COPY src $app/src

# Build the webpack bundle
RUN npx webpack

# Expose Port
EXPOSE 3030

# Start the development server
CMD ["yarn", "start"]
