version: '3.6'

services:
  axi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/opt/app/src
      - ./webpack.config.js:/opt/app/webpack.config.js
      - ./package.json:/opt/app/package.json
    ports:
      - 3030:3030
    environment:
      PORT: 3030
      SECRET: "8PH8vbJoQAg?TN^k29/DzrLkMMiWzmEZ(8"
      LOG_LEVEL: info
      DATABASE: axi
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      RABBITMQ_URL: "amqp://rabbitmq"
      REDIS_URL: "redis://redis"

  postgresql:
    build: ./tools/postgresql
    volumes:
      - ./tools/storage/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: axi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    volumes:
      - ./tools/storage/redis:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 1883:1883
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 15675:15675
    volumes:
      - ./tools/rabbitmq/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
      - ./tools/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
