version: '3.6'

services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    volumes:
      - ./storage/redis:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 1883:1883
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 15675:15675
    volumes:
      - ./config/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
