schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

# The queries that can be requested
type Query {
  # List every projects
  projects: [Project]

  # Retrieves a Project corresponding with the seat
  project(id: ID!): Project
}

# The mutations that can be performed
type Mutation {
  # Creates project
  createProject: Project
}

# The subscriptions that can be listened to
type Subscription {
  projectCreated: Project
}

# Project contains the seat number and the buyer's name
type Project {
  # ID
  id: ID!

  name: String!
  displayName: String!

  description: String
  color: String
  icon: String
}
